jQuery(document).ready(function ($) {
    'use strict'; jQuery(window).scroll(function () {
        if (jQuery(this).scrollTop() > 170) { jQuery('body').addClass("scrapcar-sticky"); }
        else { jQuery('body').removeClass("scrapcar-sticky"); }
    }); jQuery('.scrapcar-banner').slick({ slidesToShow: 1, slidesToScroll: 1, autoplay: true, autoplaySpeed: 2000, infinite: true, dots: false, prevArrow: "<span class='slick-arrow-left'><i class='icon church-arrows3'></i></span>", nextArrow: "<span class='slick-arrow-right'><i class='icon church-arrows3'></i></span>", fade: true, responsive: [{ breakpoint: 1024, settings: { slidesToShow: 1, slidesToScroll: 1, infinite: true, } }, { breakpoint: 800, settings: { slidesToShow: 1, slidesToScroll: 1 } }, { breakpoint: 400, settings: { slidesToShow: 1, slidesToScroll: 1 } }] }); $(function () { $('body').addClass('js'); var $menu = $('#menu'), $menulink = $('.menu-link'), $menuTrigger = $('.has-subnav'); $menulink.on("click", function (e) { e.preventDefault(); $menulink.toggleClass('active'); $menu.toggleClass('active'); }); $menuTrigger.on("click", function (e) { e.preventDefault(); var $this = $(this); $this.toggleClass('active').next('ul').toggleClass('active'); }); }); jQuery(".sub-menu").parent("li").addClass("subdropdown-addicon"); jQuery(".fancybox").fancybox({ openEffect: 'elastic', closeEffect: 'elastic', }); jQuery('.grid').isotope({ itemSelector: '.grid-item', percentPosition: true, masonry: { fitWidth: true } }); $(function () {
        $("#slider-range").slider({ range: true, min: 0, max: 150, values: [0, 58], slide: function (event, ui) { $("#amount").val("$" + ui.values[0] + " - $" + ui.values[1]); } }); $("#amount").val("$" + $("#slider-range").slider("values", 0) +
            " - $" + $("#slider-range").slider("values", 1));
    }); jQuery('.scrapcar-shop-thumb').slick({ slidesToShow: 1, autoplay: true, slidesToScroll: 1, arrows: false, fade: true, dots: true, asNavFor: '.scrapcar-shop-thumb-list' }); jQuery('.scrapcar-shop-thumb-list').slick({ slidesToShow: 4, slidesToScroll: 1, autoplay: true, asNavFor: '.scrapcar-shop-thumb', dots: false, arrows: false, vertical: false, centerMode: false, focusOnSelect: true, responsive: [{ breakpoint: 1024, settings: { slidesToShow: 3, slidesToScroll: 1, infinite: true, vertical: false, } }, { breakpoint: 800, settings: { slidesToShow: 3, slidesToScroll: 1, vertical: false, } }, { breakpoint: 400, settings: { slidesToShow: 2, slidesToScroll: 1, vertical: false, } }], }); jQuery('.scrapcar-testimonial').slick({ slidesToShow: 5, slidesToScroll: 1, dots: false, prevArrow: "<span class='slick-arrow-left'><i class='fa fa-angle-left'></i></span>", nextArrow: "<span class='slick-arrow-right'><i class='fa fa-angle-right'></i></span>", centerMode: true, focusOnSelect: true, variableWidth: true, responsive: [{ breakpoint: 1024, settings: { slidesToShow: 3, slidesToScroll: 1, infinite: true, vertical: false, } }, { breakpoint: 800, settings: { slidesToShow: 3, slidesToScroll: 1, vertical: false, } }, { breakpoint: 400, settings: { slidesToShow: 1, slidesToScroll: 1, vertical: false, } }], }); jQuery('.scrapcar-listing-gallery').slick({ slidesToShow: 1, autoplay: true, slidesToScroll: 1, arrows: false, fade: true, asNavFor: '.scrapcar-listing-gallery-list' }); jQuery('.scrapcar-listing-gallery-list').slick({ slidesToShow: 8, slidesToScroll: 1, autoplay: true, asNavFor: '.scrapcar-listing-gallery', dots: false, arrows: false, vertical: false, centerMode: false, focusOnSelect: true, responsive: [{ breakpoint: 1024, settings: { slidesToShow: 6, slidesToScroll: 1, infinite: true, vertical: false, } }, { breakpoint: 800, settings: { slidesToShow: 6, slidesToScroll: 1, vertical: false, } }, { breakpoint: 400, settings: { slidesToShow: 6, slidesToScroll: 1, vertical: false, } }], });
}); jQuery('video').mediaelementplayer({ success: function (player, node) { jQuery('#' + node.id + '-mode').html('mode: ' + player.pluginType); } }); jQuery('.scrapcar-listing-information .nav-tabs a').on('shown.bs.tab', function (e) {
    var target = $(e.target).attr("href")
    if (target == '#gallery') { jQuery('.scrapcar-listing-gallery-list').resize(); }
    if (target == '#location') { google.maps.event.trigger(map, 'resize'); }
});